### PR TITLE
Drop obsolete QProcess::start()

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
GTM.

You could leave comments; most of them don't make sense.

**Comment by tsujan** [comment]
Not related to the PR:

`execwindow.cpp` seems suspicious to me; absolutely don't remember what it's for. I should "attack" it in my next code cleanup.

**Comment by luis-pereira** [comment]
> You could leave comments; most of them don't make sense.

Didn't understood what you meant.

**Comment by tsujan** [comment]
```
// thread run, if null then segfault occurs. ?
```

**Comment by luis-pereira** [comment]
> // thread run, if null then segfault occurs. ?

It was in the original code. I decided to keep it.

**Comment by tsujan** [comment]
> It was in the original code.

Yes; my comment was about that.

**Comment by luis-pereira** [comment]
> Yes; my comment was about that.

It might be understandable to some people.

**Comment by luis-pereira** [comment]
Yes. It has suspicious patterns.

**Comment by tsujan** [comment]
> Yes. It has suspicious patterns.

Everything is suspicious in Qps ;)

**Pull request merged**
