### PR TITLE
Prepared the 2.0.0 release

### PR DESCRIPTION
**Pull request by agaida**
* Updated changelog
* Bumped version in CMakeLists.txt

### CODE REVIEW

**Comment by agaida** [comment]
@tsujan @shlyakpavel  - please feel free to modify the changelog to your needs

**Comment by tsujan** [comment]
I just added a short explanation about @shlyakpavel's systray fix. Everything seems OK to me.

**Comment by shlyakpavel** [comment]
`Get rid of flag_SMPsim, Get rid of FaderWidget`
Such items do not sound informative. Imo it would be better wither to explain or to drop them at all (something like internal cleanup)

**Comment by tsujan** [comment]
@shlyakpavel You could change them by adding a commit to this branch -- you're a member now.

**Pull request merged**
