### PR TITLE
Added localization support.

### PR DESCRIPTION
**Pull request by vangrtc**
const char strings replaced by QString and initialized by QObject::tr() . Changes covers the whole project. Added empty .ts-file, prepared for russion translations.

### CODE REVIEW

**Comment by agaida** [comment]
@tsujan @palinek @luis-pereira  -  can one of you please review?

**Comment by tsujan** [comment]
@agaida I took a *super fast* look at it and it seemed OK. Since it's very big and I'm busy with another LXQt project, I won't find time for a thorough review soon. I suggest you test it.

**Comment by vangrtc** [comment]
despite that the change affects many files, most of the changes are simply replaces compiled messages with loaded at runtime translated qstrings. Also currently it doesn't load any translations due to path issue.

**Comment by agaida** [comment]
@vangrtc - thank you very much for you work - applies and work fine (wow, the first 10k-lines patch since along time)

**Pull request merged**
