### PR TITLE
Proc

### PR DESCRIPTION
**Pull request by luis-pereira**
Boring, Boring stuff (proc.* files)

### CODE REVIEW

**Comment by tsujan** [comment]
> Boring, Boring stuff (proc.* files)

LOL! Yes, I know. On the bright side, the result is a huge code cleanup, which was necessary. I'll check it tomorrow.

**Comment by luis-pereira** [comment]
> EDIT: Those files you removed gave me a headache months ago, when I searched for functions ;)

Me too.... until I realized they weren't even being compiled.

**Comment by luis-pereira** [comment]
> GTM
> 
> @luis-pereira Thanks for not changing the contents of `proc_common.cpp` when transferring them to `proc.cpp` (except for a few `nullptr`); otherwise, the review would take hours.

Mmm. I was my intention to change anything.
I know how hard is to review lot's of changes in one commit. It hurts.

**Comment by tsujan** [comment]
> I know how hard is to review lot's of changes in one commit.

Not so hard with your clean PRs.

**Pull request merged**
