### PR TITLE
Cleaned up the classes SearchBox, ControlBar and StatusBar

### PR DESCRIPTION
**Pull request by tsujan**

### CODE REVIEW

**Comment by tsujan** [comment]
`event_xbutton_clicked` is kept for now although redundant (I couldn't read the coder's mind in this case).

**Comment by shlyakpavel** [comment]
Builds well, search and resizing work well

**Comment by tsujan** [comment]
Thanks! Let's get rid of it as soon as possible ;)

**Comment by tsujan** [comment]
I think we'll have to do this dirty job for months. I just hope something interesting will come out of it.

After it's done, the real job could be started: getting rid of Qt2 ways of making the GUI.

**Pull request merged**
