### PR TITLE
Remove screenshot capability

### PR DESCRIPTION
**Pull request by luis-pereira**
There are tools dedicated to screenshots.
It was being used for development purposes. A developer knows how to make
a screenshot, if needed.

### CODE REVIEW

**Comment by tsujan** [comment]
I even didn't know that are codes related to screenshot. Yes, they should be removed.

**Comment by shlyakpavel** [comment]
Cool alternative to screengrab and lximage-qt :D

**Comment by luis-pereira** [comment]
@tsujan Neither do I.

**Comment by luis-pereira** [comment]
@tsujan Forgot to ask for a review!

**Comment by tsujan** [comment]
I hadn't forgotten this; have been busy with a few GUI optimizations for pcmanfm-qt. Will review and merge it tonight.

**Comment by luis-pereira** [comment]
Thanks. That avoids resolving nasty merge conflicts.

**Comment by tsujan** [comment]
You're welcome. Yes, we shouldn't delay checking and merging of these PRs; otherwise, merge conflicts might arise easily because there are lots of things to do.

**Pull request merged**
