### PR TITLE
Use LXQt::SingleApplication

### PR DESCRIPTION
**Pull request by luis-pereira**
It supports unique application and also activation.
Introduces liblxqt as a dependency.

### CODE REVIEW

**Comment by tsujan** [comment]
Very nice.

Screengrab also needs this but, I think, it might be difficult because its code structure needs to be changed first.

**Comment by tsujan** [comment]
@agaida This is GTM. I didn't merge it only because I thought you might want to do something in Debian, because of the new dependency.

Also, see https://github.com/lxqt/qps/issues/224 (which isn't related to this PR).

**Comment by tsujan** [comment]
Oh, I forgot something:

With this patch, if Qps is started for the second time, a second tray icon (in notification area) will be shown and removed immediately. That doesn't happen without the patch.

@luis-pereira Do you know why that happens? Should the fix be in `LXQt::SingleApplication` or in Qps?

**Comment by luis-pereira** [comment]
@tsujan Didn't notice that. My first guess is something in qps itself. It's structure leads to unintentional side-effects.
Will look into it, later today.

**Comment by tsujan** [comment]
@luis-pereira It isn't important because the single-instance mode works OK, but it'll be perfect if you could remove the temporary appearance of the second tray icon.

**Comment by luis-pereira** [comment]
@tsujan The issue with the tray icon is in qps itself. It's a side effect from qps structure.
I could do a quick fix. But... I won't.
Will fix it the proper way. It will lead to changes in the code structure, that have to be done anyway.

**Comment by tsujan** [comment]
OK. The current PR is good and can be merged as it is; the temporary tray icon isn't a big deal at all.

**Comment by agaida** [comment]
@tsujan - if this dependency thing is happen again - just merge it if ok and don't care for me (only when i wearing my debian hat) - just leaving a note would be nice.

**Comment by tsujan** [comment]
@agaida 
Understood.

**Pull request merged**
