### PR TITLE
Fixed  "Fields" translation.updated translations

### PR DESCRIPTION
**Pull request by stefonarch**
Fixed also first item on menubar.

Co-authored-by: Mincho Kondarev <mkondarev@yahoo.de>

Closes https://github.com/lxqt/qps/issues/271

### CODE REVIEW

**Comment by stefonarch** [comment]
Closes https://github.com/lxqt/qps/issues/271

**Comment by tsujan** [comment]
"Fields" is good, instead of "Field".

As for "Qps", it doesn't seem better than "Command". Applications usually have "File" there but it can't be used here. I think we need to find a better word. "Application" is too long. What about "Exit"?

**Comment by stefonarch** [comment]
Maybe there is or was the intention to add more commands. There are some items in the translations that nowhere show up in the GUI (watchdog and else). 

If so "command" would make sense. "Exit" and below another "exit" is strange too.

**Comment by tsujan** [comment]
> "Exit" and below another "exit" is strange too.

I agree.

"Command", "Qps", "Application" and "Exit" are all weird.

Later, I might add some action to that menu and change it to "Actions".

**Comment by tsujan** [comment]
Oh, "Option" should be changed to "Options" too. Sorry, I don't remember where it is. Tell me if you didn't find it.

**Comment by stefonarch** [comment]
Reverted qps>command and fixed options, in italian it was plural. Updated *.ts files too.

**Review by tsujan — APPROVED** [review]
GTM

**Comment by stefonarch** [comment]
Went well in weblate, first I committed all pending stuff, then locked qps translations.

**Comment by stefonarch** [comment]
... most under "options" isn't translatable too... needs another PR

**Pull request merged**
