### PR TITLE
Replace deprecated QFontMetrics::width

### PR DESCRIPTION
**Pull request by iamthesenate1**

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
Thanks.

**Comment by tsujan** [comment]
@iamthesenate1 
If you add several commits to a PR of yours, please squash all of them after your work is finished. Alternatively, you could make the PR only after committing all changes.

It isn't necessary but makes the PR much cleaner.

**Comment by iamthesenate1** [comment]
> @iamthesenate1
> If you add several commits to a PR of yours, please squash all of them after your work is finished. Alternatively, you could make the PR only after committing all changes.
> 
> It isn't necessary but makes the PR much cleaner.

Ok. Thanks for your suggestion. But is it possible to squash commits from an already open PR?

**Comment by shlyakpavel** [comment]
> Ok. Thanks for your suggestion. But is it possible to squash commits from an already open PR?
Yes. Just squash the commits in your fork (iamthesenate1:master) and use git push --force

**Comment by shlyakpavel** [comment]
But there's nothing you can do now since this PR is already merged :)

**Comment by iamthesenate1** [comment]
> > Ok. Thanks for your suggestion. But is it possible to squash commits from an already open PR?
> 
> Yes. Just squash the commits in your fork (iamthesenate1:master) and use git push --force

Ok. Thanks.

> But there's nothing you can do now since this PR is already merged :)

I know. I was asking for future PR's.

**Pull request merged**
