### PR TITLE
Remove CMake artifacts

### PR DESCRIPTION
**Pull request by luis-pereira**
lxqt-build-tools provides it.

### CODE REVIEW

**Comment by tsujan** [comment]
GTM.

Hopefully, we might make qps' code clean in 2020.

**Comment by luis-pereira** [comment]
Hopefully. But that's a lot of work. qps code base is... challenging.

**Comment by tsujan** [comment]
Yes, it's difficult. IMO, the hardest part is making a series of PRs that can be reviewed and tested by others. Maybe, it's the right time to do so because Qps has become functional.

**Comment by luis-pereira** [comment]
> Yes, it's difficult. IMO, the hardest part is making a series of PRs that can be reviewed and tested by others. Maybe, it's the right time to do so because Qps has become functional.

Yes, and also side effects.
https://github.com/lxqt/qps/pull/219 https://github.com/lxqt/qps/pull/218 https://github.com/lxqt/qps/pull/217 are a start to clean the compiler output.

**Comment by tsujan** [comment]
> #219 #218 #217 are a start to clean the compiler output.

Yes, I saw and appreciated them. Thanks for stating it; I know how hard it is. Will check and merge the PRs tomorrow.

**Pull request merged**
